services:
  - type: web
    name: edubridge-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DEMO_MODE
        value: "false"
      - key: COOKIE_SECURE
        value: "true"
      - key: CLIENT_URL
        value: https://edubridge-as3r.onrender.com
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: edubridge-client
    runtime: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://edubridge-api-z1k5.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html