import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import cookieParser from 'cookie-parser';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import mongoose from 'mongoose';
import { User, Student, SupportRequest, AuditLog } from './models.js';

const app = express();
const port = Number(process.env.PORT || 5000);
const demoMode = process.env.DEMO_MODE === 'true';
const secret = process.env.JWT_SECRET || (demoMode ? 'edubridge-development-secret' : '');
const categories = ['Tuition Fee', 'Exam Fee', 'Study Materials', 'Transportation', 'Higher Education', 'Other Educational Support'];
const activeStatuses = ['PENDING', 'APPROVED', 'SPONSORED', 'IN_PROGRESS'];
const statuses = [...activeStatuses, 'COMPLETED', 'CANCELLED'];
const transitions = { PENDING: ['APPROVED', 'CANCELLED'], APPROVED: ['SPONSORED', 'CANCELLED'], SPONSORED: ['IN_PROGRESS', 'CANCELLED'], IN_PROGRESS: ['COMPLETED', 'CANCELLED'], COMPLETED: [], CANCELLED: [] };
const memory = { users: [], students: [], supports: [], auditLogs: [] };
const makeId = () => Math.random().toString(36).slice(2, 12);
const send = (res, data, message = 'Success') => res.json({ success: true, message, data });
const error = (res, status, message) => res.status(status).json({ success: false, message });
const plain = value => value?.toObject ? value.toObject() : value;
const userView = user => ({ id: String(user._id || user.id), name: user.name, email: user.email, role: user.role, status: user.status, isVerified: user.isVerified, profile: user.profile || {} });

function scoreStudent(data) {
  const income = Number(data.familyIncome) || 0;
  const incomeScore = income <= 5000 ? 30 : income <= 12000 ? 22 : income <= 25000 ? 12 : 4;
  const familyScore = Math.min(20, Math.max(0, (Number(data.familySize) || 1) * 3));
  const needScore = { high: 25, medium: 16, low: 8 }[String(data.educationalNeed || '').toLowerCase()] || 15;
  const dropoutScore = { high: 20, medium: 12, low: 4 }[String(data.dropoutRisk || '').toLowerCase()] || 10;
  const academicScore = Math.min(10, Math.max(0, Number(data.academicPerformance || 0) / 10));
  const amountScore = Math.min(10, Math.max(0, 10 - Number(data.requiredAmount || 0) / 20000));
  const needScoreValue = Math.round(Math.min(100, incomeScore + familyScore + needScore + dropoutScore + academicScore + amountScore));
  const priority = needScoreValue >= 80 ? 'HIGH' : needScoreValue >= 50 ? 'MEDIUM' : 'LOW';
  const explanation = priority === 'HIGH' ? 'High financial pressure and educational barriers indicate urgent support need.' : priority === 'MEDIUM' ? 'Meaningful financial and educational barriers indicate timely support would help.' : 'The student has lower immediate need indicators, while continued support can sustain progress.';
  return { needScore: needScoreValue, score: needScoreValue, priority, dropoutRisk: String(data.dropoutRisk || 'medium').toLowerCase(), aiExplanation: explanation, explanation };
}
async function analyzeStudent(data) {
  const fallback = scoreStudent(data);
  if (!process.env.OPENAI_API_KEY) return fallback;
  try {
    const response = await fetch('https://api.openai.com/v1/chat/completions', { method: 'POST', headers: { Authorization: `Bearer ${process.env.OPENAI_API_KEY}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: process.env.OPENAI_MODEL || 'gpt-4o-mini', temperature: 0, response_format: { type: 'json_object' }, messages: [{ role: 'system', content: 'Return JSON with needScore (0-100), priority (HIGH, MEDIUM, LOW), dropoutRisk, and aiExplanation. This is decision support only and must never approve or reject eligibility.' }, { role: 'user', content: JSON.stringify(data) }] }) });
    if (!response.ok) return fallback;
    const result = await response.json();
    const parsed = JSON.parse(result.choices?.[0]?.message?.content || '{}');
    if (!Number.isFinite(Number(parsed.needScore)) || !['HIGH', 'MEDIUM', 'LOW'].includes(parsed.priority)) return fallback;
    const needScore = Math.max(0, Math.min(100, Math.round(Number(parsed.needScore))));
    return { ...fallback, needScore, score: needScore, priority: parsed.priority, dropoutRisk: String(parsed.dropoutRisk || fallback.dropoutRisk).toLowerCase(), aiExplanation: String(parsed.aiExplanation || fallback.aiExplanation).slice(0, 1000), explanation: String(parsed.aiExplanation || fallback.explanation).slice(0, 1000), scoringVersion: 'openai-v1' };
  } catch { return fallback; }
}
const tokenFor = user => jwt.sign({ id: String(user._id || user.id), role: user.role }, secret, { expiresIn: '7d' });
const setSession = (res, user) => res.cookie('edubridge_session', tokenFor(user), { httpOnly: true, sameSite: 'lax', secure: process.env.COOKIE_SECURE === 'true', maxAge: 7 * 86400000 });
const getUser = id => demoMode ? memory.users.find(item => item.id === id) : User.findById(id);
const getStudents = () => demoMode ? Promise.resolve(memory.students) : Student.find().lean();
const getSupports = () => demoMode ? Promise.resolve(memory.supports) : SupportRequest.find().lean();
const getStudent = id => demoMode ? Promise.resolve(memory.students.find(item => item.id === id)) : Student.findById(id).lean();
const auth = async (req, res, next) => { try { const raw = req.cookies.edubridge_session || String(req.headers.authorization || '').replace(/^Bearer\s+/i, ''); const payload = jwt.verify(raw, secret); const user = await getUser(payload.id); if (!user || user.status === 'BLOCKED') return error(res, 401, 'Your session is no longer active.'); req.user = user; next(); } catch { error(res, 401, 'Authentication required.'); } };
const allow = (...roles) => (req, res, next) => roles.includes(req.user.role) ? next() : error(res, 403, 'You do not have permission for this action.');
const audit = async (user, action, entityType, entityId, description) => { const entry = { userId: String(user?._id || user?.id || ''), action, entityType, entityId: String(entityId), description, timestamp: new Date() }; if (demoMode) memory.auditLogs.unshift({ ...entry, id: makeId() }); else await AuditLog.create(entry); };

app.set('trust proxy', 1);
app.use(helmet());
const allowedOrigin = (origin, callback) => {
  const configured = process.env.CLIENT_URL || 'http://localhost:5173';
  const codespacesOrigin = /^https:\/\/[^/]+-(5173|5174)\.app\.github\.dev$/;
  if (!origin || origin === configured || origin === 'http://localhost:5173' || origin === 'http://localhost:5174' || codespacesOrigin.test(origin)) return callback(null, true);
  return callback(new Error('Origin is not allowed by CORS.'));
};
app.use(cors({ origin: allowedOrigin, credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.use(cookieParser());
app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: 300 }));

async function seedDemo() {
  if (!demoMode || memory.users.length) return;
  const password = await bcrypt.hash('EduBridge2026!', 10);
  memory.users.push({ id: 'admin-001', name: 'Maya Thompson', email: 'admin@edubridge.demo', password, role: 'ADMIN', status: 'ACTIVE', isVerified: true, profile: {} });
  memory.users.push({ id: 'vol-001', name: 'Amina Yusuf', email: 'volunteer@edubridge.demo', password, role: 'VOLUNTEER', status: 'ACTIVE', isVerified: true, profile: { verificationStatus: 'APPROVED', location: 'Nairobi' } });
  memory.users.push({ id: 'sponsor-001', name: 'Northstar Foundation', email: 'sponsor@edubridge.demo', password, role: 'SPONSOR', status: 'ACTIVE', isVerified: true, profile: { budget: 75000, location: 'Nairobi', preferredCategories: ['Tuition Fee', 'Study Materials'] } });
  const names = ['Brian Otieno', 'Lydia Wanjiku', 'Samuel Kariuki', 'Zawadi Njeri', 'Peter Mwangi', 'Grace Achieng', 'Daniel Kimani', 'Irene Wambui', 'Joel Ouma', 'Faith Chebet'];
  names.forEach((name, index) => { const data = { familyIncome: 4000 + index * 1800, familySize: 3 + index % 5, educationalNeed: index < 4 ? 'high' : 'medium', dropoutRisk: index < 3 ? 'high' : 'medium', academicPerformance: 62 + index * 3, requiredAmount: 8000 + index * 1750 }; memory.students.push({ id: `student-${index + 1}`, name, age: 12 + index % 7, school: index % 2 ? 'Makadara Secondary' : 'Eastlands Academy', location: 'Nairobi', supportCategory: categories[index % 3], description: 'A motivated learner seeking support to continue their education.', submittedBy: 'vol-001', verificationStatus: 'APPROVED', ...data, ...scoreStudent(data), createdAt: new Date().toISOString() }); });
}

app.get('/api/health', (_, res) => send(res, { status: 'ok', database: demoMode ? 'demo-mode' : mongoose.connection.readyState === 1 ? 'mongodb' : 'connecting' }));
app.post('/api/auth/register', async (req, res, next) => { try { const { name, email, password, role } = req.body; if (!name || !email || !password || password.length < 8) return error(res, 422, 'Name, email, and a password of at least 8 characters are required.'); if (!['VOLUNTEER', 'SPONSOR'].includes(role)) return error(res, 422, 'Choose a valid account type.'); const normalized = email.trim().toLowerCase(); const exists = demoMode ? memory.users.some(item => item.email === normalized) : await User.exists({ email: normalized }); if (exists) return error(res, 422, 'An account with this email already exists.'); const data = { name: name.trim(), email: normalized, password: await bcrypt.hash(password, 10), role, status: 'ACTIVE', isVerified: role === 'SPONSOR', profile: role === 'SPONSOR' ? { budget: 0, preferredCategories: [] } : { verificationStatus: 'PENDING' } }; const user = demoMode ? (memory.users.push({ ...data, id: makeId() }), memory.users.at(-1)) : await User.create(data); setSession(res, user); send(res, { user: userView(user) }, 'Account created'); } catch (e) { next(e); } });
app.post('/api/auth/login', async (req, res, next) => { try { const email = String(req.body.email || '').trim().toLowerCase(); const user = demoMode ? memory.users.find(item => item.email === email) : await User.findOne({ email }).select('+password'); if (!user || !(await bcrypt.compare(req.body.password || '', user.password))) return error(res, 401, 'Email or password is incorrect.'); if (user.status === 'BLOCKED') return error(res, 403, 'This account has been blocked.'); setSession(res, user); send(res, { user: userView(user) }, 'Welcome back'); } catch (e) { next(e); } });
app.post('/api/auth/logout', (_, res) => { res.clearCookie('edubridge_session'); send(res, null, 'Signed out'); });
app.get('/api/auth/me', auth, (req, res) => send(res, userView(req.user)));
app.patch('/api/profile', auth, async (req, res, next) => { try { const profile = { ...(req.user.profile || {}), ...req.body }; if (req.user.role === 'SPONSOR') { profile.budget = Math.max(0, Number(profile.budget || 0)); profile.preferredCategories = Array.isArray(profile.preferredCategories) ? profile.preferredCategories.filter(item => categories.includes(item)) : categories.includes(profile.preferredCategories) ? [profile.preferredCategories] : []; } if (demoMode) req.user.profile = profile; else { req.user.profile = profile; await req.user.save(); } send(res, userView(req.user), 'Profile updated'); } catch (e) { next(e); } });
app.post('/api/verification', auth, allow('VOLUNTEER'), async (req, res, next) => { try { const profile = { ...(req.user.profile || {}), ...req.body, verificationStatus: 'PENDING' }; req.user.profile = profile; req.user.isVerified = false; if (!demoMode) await req.user.save(); await audit(req.user, 'SUBMIT', 'VolunteerVerification', req.user._id || req.user.id, 'Submitted volunteer verification details.'); send(res, userView(req.user), 'Verification submitted'); } catch (e) { next(e); } });
app.get('/api/stats', async (_, res, next) => { try { const [students, supports] = await Promise.all([getStudents(), getSupports()]); const users = demoMode ? memory.users : await User.find().lean(); send(res, { studentsSupported: supports.filter(item => item.status === 'COMPLETED').length, activeVolunteers: users.filter(item => item.role === 'VOLUNTEER' && item.isVerified).length, sponsors: users.filter(item => item.role === 'SPONSOR').length, supportProvided: supports.reduce((sum, item) => sum + Number(item.amount), 0) }); } catch (e) { next(e); } });
app.get('/api/students', auth, async (req, res, next) => { try { let data = await getStudents(); if (req.user.role === 'VOLUNTEER') data = data.filter(item => String(item.submittedBy) === String(req.user._id || req.user.id)); if (req.user.role === 'SPONSOR') data = data.filter(item => item.verificationStatus === 'APPROVED'); if (req.query.search) data = data.filter(item => item.name.toLowerCase().includes(String(req.query.search).toLowerCase())); if (req.query.category) data = data.filter(item => item.supportCategory === req.query.category); data.sort((a, b) => Number(b.needScore ?? b.score) - Number(a.needScore ?? a.score)); send(res, data); } catch (e) { next(e); } });
app.get('/api/students/:id', auth, async (req, res, next) => { try { const student = await getStudent(req.params.id); if (!student) return error(res, 404, 'Student not found.'); if (req.user.role === 'VOLUNTEER' && String(student.submittedBy) !== String(req.user._id || req.user.id)) return error(res, 403, 'You do not have access to this student.'); const supports = (await getSupports()).filter(item => String(item.studentId) === String(student._id || student.id)); send(res, { ...plain(student), supports }); } catch (e) { next(e); } });
app.post('/api/students', auth, allow('VOLUNTEER'), async (req, res, next) => { try { if (!req.user.isVerified) return error(res, 403, 'Volunteer verification approval is required before adding students.'); const body = req.body; if (!body.name || !body.school || Number(body.familyIncome) < 0 || Number(body.familySize) < 1 || !categories.includes(body.supportCategory) || Number(body.requiredAmount) <= 0) return error(res, 422, 'Please provide valid student details and support information.'); const analysis = await analyzeStudent(body); const data = { ...body, age: Number(body.age || 0), familyIncome: Number(body.familyIncome), familySize: Number(body.familySize), requiredAmount: Number(body.requiredAmount), academicPerformance: Number(body.academicPerformance || 0), submittedBy: req.user._id || req.user.id, verificationStatus: 'PENDING', scoringVersion: analysis.scoringVersion || 'deterministic-v1', analyzedAt: new Date(), ...analysis }; const student = demoMode ? (memory.students.unshift({ ...data, id: makeId(), createdAt: new Date().toISOString() }), memory.students[0]) : await Student.create(data); await audit(req.user, 'CREATE', 'Student', student._id || student.id, `Submitted ${student.name} for review.`); send(res, plain(student), 'Student submitted for review'); } catch (e) { next(e); } });
app.post('/api/ai/analyze-student', auth, allow('VOLUNTEER', 'ADMIN'), async (req, res, next) => { try { send(res, await analyzeStudent(req.body), 'Need analysis complete'); } catch (e) { next(e); } });
app.get('/api/recommendations/students', auth, allow('SPONSOR'), async (req, res, next) => { try { const sponsor = req.user.profile || {}; const supports = await getSupports(); const data = (await getStudents()).filter(student => student.verificationStatus === 'APPROVED' && !supports.some(item => String(item.studentId) === String(student._id || student.id) && activeStatuses.includes(item.status))).map(student => { const categoryMatch = sponsor.preferredCategories?.includes(student.supportCategory); const locationMatch = sponsor.location && student.location && sponsor.location.toLowerCase() === student.location.toLowerCase(); const affordable = Number(student.requiredAmount) <= Number(sponsor.budget || 0); const reasons = [categoryMatch && 'matches your preferred category', affordable && 'fits your available budget', locationMatch && 'is in your preferred location'].filter(Boolean); return { ...plain(student), recommendationReason: reasons.length ? `${reasons.join(', ')} and has a verified need profile.` : 'A strong opportunity to create immediate educational impact.', matchReason: reasons.length ? reasons.join(', ') : 'Strong educational impact opportunity.', matchScore: (categoryMatch ? 30 : 0) + (affordable ? 25 : 0) + (locationMatch ? 15 : 0) + Number(student.needScore ?? student.score) / 2 }; }).sort((a, b) => b.matchScore - a.matchScore); send(res, data); } catch (e) { next(e); } });
app.post('/api/support', auth, allow('SPONSOR'), async (req, res, next) => { try { const student = await getStudent(req.body.studentId); const amount = Number(req.body.amount || student?.requiredAmount); if (!student) return error(res, 404, 'Student not found.'); if (student.verificationStatus !== 'APPROVED') return error(res, 422, 'Only approved students can receive support.'); const supports = await getSupports(); if (supports.some(item => String(item.studentId) === String(student._id || student.id) && activeStatuses.includes(item.status))) return error(res, 409, 'This student already has an active sponsorship.'); const sponsorId = req.user._id || req.user.id; const used = supports.filter(item => String(item.sponsorId) === String(sponsorId) && item.status !== 'CANCELLED').reduce((sum, item) => sum + Number(item.amount), 0); if (amount <= 0 || amount > Number(student.requiredAmount) || amount + used > Number(req.user.profile?.budget || 0)) return error(res, 422, 'Support amount exceeds the student requirement or your available budget.'); const data = { studentId: student._id || student.id, sponsorId, amount, category: student.supportCategory, status: 'PENDING', notes: req.body.notes || '' }; const support = demoMode ? (memory.supports.unshift({ ...data, id: makeId(), createdAt: new Date().toISOString() }), memory.supports[0]) : await SupportRequest.create(data); await audit(req.user, 'CREATE', 'SupportRequest', support._id || support.id, `Started support for ${student.name}.`); send(res, plain(support), 'Support request created'); } catch (e) { next(e); } });
app.get('/api/support', auth, async (req, res, next) => { try { const supports = await getSupports(); const students = await getStudents(); const userId = String(req.user._id || req.user.id); const visible = req.user.role === 'ADMIN' ? supports : supports.filter(item => String(item.sponsorId) === userId || (req.user.role === 'VOLUNTEER' && String(students.find(student => String(student._id || student.id) === String(item.studentId))?.submittedBy) === userId)); send(res, visible.map(item => ({ ...plain(item), student: students.find(student => String(student._id || student.id) === String(item.studentId))?.name }))); } catch (e) { next(e); } });
app.patch('/api/support/:id', auth, allow('ADMIN'), async (req, res, next) => { try { if (!statuses.includes(req.body.status)) return error(res, 422, 'Invalid support status.'); const support = demoMode ? memory.supports.find(item => item.id === req.params.id) : await SupportRequest.findById(req.params.id); if (!support) return error(res, 404, 'Support record not found.'); if (!transitions[support.status]?.includes(req.body.status)) return error(res, 422, `Cannot move support from ${support.status} to ${req.body.status}.`); support.status = req.body.status; support.notes = req.body.notes ?? support.notes; if (!demoMode) await support.save(); await audit(req.user, 'UPDATE_STATUS', 'SupportRequest', req.params.id, `Status changed to ${support.status}.`); send(res, plain(support), 'Support status updated'); } catch (e) { next(e); } });
app.get('/api/admin/overview', auth, allow('ADMIN'), async (_, res, next) => { try { const users = demoMode ? memory.users : await User.find().lean(); const [students, supports] = await Promise.all([getStudents(), getSupports()]); send(res, { users: users.length, volunteers: users.filter(item => item.role === 'VOLUNTEER').length, verifiedVolunteers: users.filter(item => item.role === 'VOLUNTEER' && item.isVerified).length, sponsors: users.filter(item => item.role === 'SPONSOR').length, students: students.length, highPriority: students.filter(item => item.priority === 'HIGH').length, activeSupport: supports.filter(item => activeStatuses.includes(item.status)).length, completed: supports.filter(item => item.status === 'COMPLETED').length, totalAmount: supports.reduce((sum, item) => sum + Number(item.amount), 0), priority: ['HIGH', 'MEDIUM', 'LOW'].map(name => ({ name, value: students.filter(item => item.priority === name).length })), supportStatus: statuses.map(name => ({ name, value: supports.filter(item => item.status === name).length })), categories: categories.map(name => ({ name, value: students.filter(item => item.supportCategory === name).length })) }); } catch (e) { next(e); } });
app.get('/api/admin/volunteers', auth, allow('ADMIN'), async (_, res, next) => { try { const users = demoMode ? memory.users : await User.find().lean(); send(res, users.filter(item => item.role === 'VOLUNTEER').map(userView)); } catch (e) { next(e); } });
app.patch('/api/admin/volunteers/:id', auth, allow('ADMIN'), async (req, res, next) => { try { const state = req.body.status; if (!['APPROVED', 'REJECTED', 'BLOCKED', 'ACTIVE'].includes(state)) return error(res, 422, 'Invalid volunteer status.'); const user = demoMode ? memory.users.find(item => item.id === req.params.id) : await User.findById(req.params.id); if (!user || user.role !== 'VOLUNTEER') return error(res, 404, 'Volunteer not found.'); user.isVerified = state === 'APPROVED'; user.status = state === 'BLOCKED' ? 'BLOCKED' : 'ACTIVE'; user.profile = { ...user.profile, verificationStatus: state }; if (!demoMode) await user.save(); await audit(req.user, state, 'Volunteer', req.params.id, `${state} volunteer verification.`); send(res, userView(user), 'Volunteer updated'); } catch (e) { next(e); } });
app.get('/api/admin/sponsors', auth, allow('ADMIN'), async (_, res, next) => { try { const users = demoMode ? memory.users : await User.find().lean(); send(res, users.filter(item => item.role === 'SPONSOR').map(userView)); } catch (e) { next(e); } });
app.patch('/api/admin/students/:id', auth, allow('ADMIN'), async (req, res, next) => { try { if (!['APPROVED', 'REJECTED', 'PENDING'].includes(req.body.status)) return error(res, 422, 'Invalid student review status.'); const student = demoMode ? memory.students.find(item => item.id === req.params.id) : await Student.findById(req.params.id); if (!student) return error(res, 404, 'Student not found.'); student.verificationStatus = req.body.status; if (!demoMode) await student.save(); await audit(req.user, 'REVIEW', 'Student', req.params.id, `Student review changed to ${req.body.status}.`); send(res, plain(student), 'Student review updated'); } catch (e) { next(e); } });
app.get('/api/admin/audit-logs', auth, allow('ADMIN'), async (_, res, next) => { try { send(res, demoMode ? memory.auditLogs : await AuditLog.find().sort({ timestamp: -1 }).limit(500).lean()); } catch (e) { next(e); } });
app.use((_, res) => error(res, 404, 'Route not found.'));
app.use((e, _, res, __) => { console.error(e); error(res, e.name === 'ValidationError' ? 422 : 500, e.name === 'ValidationError' ? 'Request validation failed.' : 'Something went wrong on the server.'); });

async function start() { if (!demoMode && (!process.env.MONGODB_URI || !process.env.JWT_SECRET)) throw new Error('MONGODB_URI and JWT_SECRET are required. Set DEMO_MODE=true for an explicit local demo.'); await seedDemo(); if (!demoMode) { await mongoose.connect(process.env.MONGODB_URI); console.log('MongoDB connected.'); } app.listen(port, '0.0.0.0', () => console.log(`EduBridge API listening on 0.0.0.0:${port} (${demoMode ? 'demo mode' : 'MongoDB mode'})`)); }
if (process.env.NODE_ENV !== 'test') start().catch(e => { console.error(e); process.exit(1); });
export { scoreStudent };
export default app;
